import json
import os
from datetime import datetime
from pathlib import Path
from rich.console import Console

console = Console()

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Recon Report — {domain}</title>
<style>
  :root {{
    --bg: #0d1117; --bg2: #161b22; --bg3: #21262d;
    --border: #30363d; --text: #e6edf3; --text2: #8b949e;
    --cyan: #58a6ff; --green: #3fb950; --yellow: #d29922;
    --red: #f85149; --purple: #bc8cff; --orange: #ffa657;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; padding: 2rem; }}
  .header {{ border-bottom: 1px solid var(--border); padding-bottom: 1.5rem; margin-bottom: 2rem; }}
  .header h1 {{ font-size: 1.8rem; color: var(--cyan); }}
  .header .meta {{ color: var(--text2); margin-top: 0.5rem; font-size: 0.9rem; }}
  .badge {{ display: inline-block; padding: 0.2rem 0.7rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; margin-right: 0.4rem; }}
  .badge-red {{ background: rgba(248,81,73,0.15); color: var(--red); border: 1px solid rgba(248,81,73,0.3); }}
  .badge-yellow {{ background: rgba(210,153,34,0.15); color: var(--yellow); border: 1px solid rgba(210,153,34,0.3); }}
  .badge-green {{ background: rgba(63,185,80,0.15); color: var(--green); border: 1px solid rgba(63,185,80,0.3); }}
  .badge-cyan {{ background: rgba(88,166,255,0.15); color: var(--cyan); border: 1px solid rgba(88,166,255,0.3); }}
  .section {{ background: var(--bg2); border: 1px solid var(--border); border-radius: 8px; margin-bottom: 1.5rem; overflow: hidden; }}
  .section-header {{ padding: 1rem 1.5rem; background: var(--bg3); border-bottom: 1px solid var(--border); display: flex; align-items: center; gap: 0.75rem; }}
  .section-header h2 {{ font-size: 1rem; font-weight: 600; }}
  .section-header .icon {{ font-size: 1.2rem; }}
  .section-body {{ padding: 1.5rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
  th {{ text-align: left; padding: 0.6rem 1rem; background: var(--bg3); color: var(--text2); font-weight: 500; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  td {{ padding: 0.6rem 1rem; border-top: 1px solid var(--border); vertical-align: top; word-break: break-all; }}
  tr:hover td {{ background: rgba(255,255,255,0.02); }}
  .tag {{ display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 500; }}
  .tag-green {{ background: rgba(63,185,80,0.15); color: var(--green); }}
  .tag-red {{ background: rgba(248,81,73,0.15); color: var(--red); }}
  .tag-yellow {{ background: rgba(210,153,34,0.15); color: var(--yellow); }}
  .tag-cyan {{ background: rgba(88,166,255,0.15); color: var(--cyan); }}
  .tag-gray {{ background: rgba(139,148,158,0.15); color: var(--text2); }}
  .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; }}
  .stat-card {{ background: var(--bg3); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }}
  .stat-card .num {{ font-size: 2rem; font-weight: 700; color: var(--cyan); }}
  .stat-card .label {{ font-size: 0.8rem; color: var(--text2); margin-top: 0.25rem; }}
  .empty {{ color: var(--text2); font-style: italic; text-align: center; padding: 2rem; }}
  .footer {{ text-align: center; color: var(--text2); font-size: 0.8rem; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); }}
  code {{ font-family: 'Cascadia Code', 'Fira Code', monospace; font-size: 0.85em; background: var(--bg3); padding: 0.1rem 0.4rem; border-radius: 3px; }}
</style>
</head>
<body>
<div class="header">
  <h1>🔍 Recon Report</h1>
  <div class="meta">
    Target: <strong style="color:var(--cyan)">{domain}</strong> &nbsp;|&nbsp;
    Generated: <strong>{timestamp}</strong> &nbsp;|&nbsp;
    Tool: <a href="https://github.com/liketosweep/recon-toolkit" style="color:var(--cyan)">recon-toolkit v2.0</a>
  </div>
</div>

{summary_section}
{subdomains_section}
{ports_section}
{dns_section}
{ssl_section}
{http_section}
{techs_section}
{vuln_section}
{wayback_section}

<div class="footer">Generated by <strong>Recon Toolkit v2.0</strong> — For authorized security testing only</div>
</body>
</html>
"""


def _badge(text, level):
    cls = {"high": "red", "medium": "yellow", "low": "cyan", "ok": "green", "info": "gray"}.get(level.lower(), "gray")
    return f'<span class="badge badge-{cls}">{text}</span>'


def _tag(text, color="gray"):
    return f'<span class="tag tag-{color}">{text}</span>'


def build_summary(data):
    sub_count = len(data.get("subdomains", []))
    port_count = len(data.get("ports", []))
    vuln = data.get("vulnerabilities", {})
    vuln_count = sum(1 for v in vuln.values() if isinstance(v, dict) and v.get("vulnerable")) if vuln else 0
    tech_count = len(data.get("technologies", {}).get("technologies", []))

    return f"""
<div class="section">
  <div class="section-header"><span class="icon">📊</span><h2>Summary</h2></div>
  <div class="section-body">
    <div class="stat-grid">
      <div class="stat-card"><div class="num">{sub_count}</div><div class="label">Subdomains</div></div>
      <div class="stat-card"><div class="num">{port_count}</div><div class="label">Open Ports</div></div>
      <div class="stat-card"><div class="num">{tech_count}</div><div class="label">Technologies</div></div>
      <div class="stat-card"><div class="num" style="color:var(--{'red' if vuln_count else 'green'})">{vuln_count}</div><div class="label">Vulnerabilities</div></div>
    </div>
  </div>
</div>"""


def build_subdomains(data):
    subs = data.get("subdomains", [])
    if not subs:
        return ""
    rows = "".join(f"<tr><td><code>{s}</code></td></tr>" for s in sorted(subs))
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">🌐</span><h2>Subdomains <span style="color:var(--text2);font-weight:400">({len(subs)})</span></h2></div>
  <div class="section-body">
    <table><thead><tr><th>Subdomain</th></tr></thead><tbody>{rows}</tbody></table>
  </div>
</div>"""


def build_ports(data):
    ports = data.get("ports", [])
    if not ports:
        return ""
    rows = ""
    for p in ports:
        risk = p.get("risky", False)
        color = "red" if risk else "green"
        rows += f"<tr><td><code>{p['port']}</code></td><td>{_tag(p['service'], color)}</td><td>{'⚠️ Risky' if risk else ''}</td></tr>"
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">🔌</span><h2>Open Ports <span style="color:var(--text2);font-weight:400">({len(ports)})</span></h2></div>
  <div class="section-body">
    <table><thead><tr><th>Port</th><th>Service</th><th>Note</th></tr></thead><tbody>{rows}</tbody></table>
  </div>
</div>"""


def build_dns(data):
    dns = data.get("dns", {})
    if not dns:
        return ""
    rows = ""
    for rtype, records in dns.items():
        if rtype in ("zone_transfer", "email_security") or not isinstance(records, list):
            continue
        for record in records:
            rows += f"<tr><td>{_tag(rtype, 'cyan')}</td><td><code>{record}</code></td></tr>"
    em = dns.get("email_security", {})
    if em:
        rows += f"<tr><td colspan='2' style='padding-top:1rem'><strong>Email Security:</strong> SPF: {_tag('Present','green') if em.get('spf') else _tag('Missing','red')} &nbsp; DMARC: {_tag('Present','green') if em.get('dmarc') else _tag('Missing','red')}</td></tr>"
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">🌍</span><h2>DNS Records</h2></div>
  <div class="section-body">
    <table><thead><tr><th>Type</th><th>Value</th></tr></thead><tbody>{rows}</tbody></table>
  </div>
</div>"""


def build_ssl(data):
    ssl = data.get("ssl", {})
    if not ssl:
        return ""
    days = ssl.get("days_left")
    exp_tag = _tag(f"{days} days left", "green" if days and days > 30 else "red")
    sans = ssl.get("sans", [])
    sans_html = " ".join(f"<code>{s}</code>" for s in sans[:15])
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">🔒</span><h2>SSL/TLS Certificate</h2></div>
  <div class="section-body">
    <table>
      <tr><td><strong>Subject</strong></td><td><code>{ssl.get('subject', {}).get('commonName','N/A')}</code></td></tr>
      <tr><td><strong>Issuer</strong></td><td>{ssl.get('issuer', {}).get('organizationName','N/A')}</td></tr>
      <tr><td><strong>Expires</strong></td><td>{ssl.get('expires','N/A')} {exp_tag}</td></tr>
      <tr><td><strong>TLS Version</strong></td><td>{_tag(ssl.get('tls_version','?'), 'green' if ssl.get('tls_version','') in ['TLSv1.2','TLSv1.3'] else 'red')}</td></tr>
      <tr><td><strong>SANs ({len(sans)})</strong></td><td>{sans_html}</td></tr>
    </table>
  </div>
</div>"""


def build_http(data):
    http = data.get("http_analysis", {})
    if not http:
        return ""
    present = http.get("present_headers", {})
    missing = http.get("missing_headers", [])
    rows = ""
    for h, v in present.items():
        rows += f"<tr><td>{_tag('✓', 'green')} <code>{h}</code></td><td style='color:var(--text2)'>{str(v)[:80]}</td></tr>"
    for h in missing:
        rows += f"<tr><td>{_tag('✗', 'red')} <code>{h}</code></td><td style='color:var(--red)'>Missing</td></tr>"
    leaks = http.get("info_leakage", {})
    if leaks:
        for h, v in leaks.items():
            rows += f"<tr><td>{_tag('⚠', 'yellow')} <code>{h}</code></td><td style='color:var(--yellow)'>{v} — Information leakage</td></tr>"
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">🛡️</span><h2>HTTP Security Headers</h2></div>
  <div class="section-body">
    <table><thead><tr><th>Header</th><th>Value / Status</th></tr></thead><tbody>{rows}</tbody></table>
  </div>
</div>"""


def build_techs(data):
    techs = data.get("technologies", {}).get("technologies", [])
    if not techs:
        return ""
    tags = " ".join(_tag(t, "cyan") for t in techs)
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">⚙️</span><h2>Technology Stack <span style="color:var(--text2);font-weight:400">({len(techs)} detected)</span></h2></div>
  <div class="section-body">{tags}</div>
</div>"""


def build_vulns(data):
    vuln = data.get("vulnerabilities", {})
    if not vuln:
        return ""
    rows = ""
    severity_map = {
        "open_redirect": ("Open Redirect", "HIGH"),
        "reflected_xss": ("Reflected XSS", "HIGH"),
        "cors": ("CORS Misconfiguration", "MEDIUM"),
        "clickjacking": ("Clickjacking", "MEDIUM"),
        "dangerous_methods": ("Dangerous HTTP Methods", "LOW"),
        "robots_exposure": ("Robots.txt Exposure", "INFO"),
        "rate_limiting": ("Rate Limiting Absent", "LOW"),
        "security_txt": ("security.txt", "INFO"),
    }
    for key, (label, sev) in severity_map.items():
        v = vuln.get(key)
        if v is None:
            continue
        is_vuln = v if isinstance(v, bool) else (v.get("vulnerable", False) if isinstance(v, dict) else bool(v))
        color = {"HIGH": "red", "MEDIUM": "yellow", "LOW": "cyan", "INFO": "gray"}[sev]
        status = _tag("VULNERABLE", "red") if is_vuln else _tag("OK", "green")
        rows += f"<tr><td>{label}</td><td>{_tag(sev, color)}</td><td>{status}</td></tr>"
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">🚨</span><h2>Vulnerability Checks</h2></div>
  <div class="section-body">
    <table><thead><tr><th>Check</th><th>Severity</th><th>Result</th></tr></thead><tbody>{rows}</tbody></table>
  </div>
</div>"""


def build_wayback(data):
    wb = data.get("wayback", {})
    if not wb:
        return ""
    total = wb.get("total_urls", 0)
    params = wb.get("parameters", [])
    interesting = wb.get("interesting_paths", [])
    subs = wb.get("subdomains", [])
    content = f"<p style='color:var(--text2);margin-bottom:1rem'>Total archived URLs: <strong style='color:var(--cyan)'>{total}</strong></p>"
    if interesting:
        content += "<strong>Interesting Paths:</strong><br>" + "".join(f"<code style='display:block;margin:0.2rem 0;font-size:0.8rem'>{p}</code>" for p in interesting[:10])
    if params:
        content += f"<br><strong>Query Parameters ({len(params)}):</strong><br>" + " ".join(_tag(p, "yellow") for p in params[:20])
    if subs:
        content += f"<br><br><strong>Subdomains from Wayback ({len(subs)}):</strong><br>" + " ".join(f"<code>{s}</code>" for s in subs[:15])
    return f"""
<div class="section">
  <div class="section-header"><span class="icon">📼</span><h2>Wayback Machine</h2></div>
  <div class="section-body">{content}</div>
</div>"""


def save(domain, data, output_dir="reports"):
    """Save both JSON and HTML reports"""
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_domain = domain.replace(".", "_")
    base = f"{output_dir}/{safe_domain}_{timestamp}"

    # JSON
    json_path = f"{base}.json"
    with open(json_path, "w") as f:
        json.dump(data, f, indent=2, default=str)

    # HTML
    html_path = f"{base}.html"
    ts_display = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    html = HTML_TEMPLATE.format(
        domain=domain,
        timestamp=ts_display,
        summary_section=build_summary(data),
        subdomains_section=build_subdomains(data),
        ports_section=build_ports(data),
        dns_section=build_dns(data),
        ssl_section=build_ssl(data),
        http_section=build_http(data),
        techs_section=build_techs(data),
        vuln_section=build_vulns(data),
        wayback_section=build_wayback(data),
    )
    with open(html_path, "w") as f:
        f.write(html)

    return json_path, html_path
